--- #YAML:1.0
name:               Biblio-Thesaurus-ModRewrite
version:            0.03
abstract:           a module to manipulate ontologies
author:
    - Nuno Carvalho <smash@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Biblio::Thesaurus:  0
    Parse::Yapp:        0
    Test::More:         0
    Test::Output:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
