--- #YAML:1.0
name:                Biblio-Thesaurus-ModRewrite
version:             0.01
abstract:            The great new Biblio::Thesaurus::ModRewrite!
license:             ~
author:              
    - Nuno Carvalho <smash@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Test::Output:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
